title      : 洛书
lang       : zh
description: 赛博空间生存手册
copyright  : © 2021 Steveeyre All Rights Reserved

nav:
 - name: 首页
   link: /
 - name: Obsidian
   link: /Obsidian
 - name: Notes
   link: /Notes
